import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:hive/hive.dart';
import 'package:uuid/uuid.dart';
import 'product_model.dart';

class AddProductScreen extends StatefulWidget {
  const AddProductScreen({super.key});

    @override
      State<AddProductScreen> createState() => _AddProductScreenState();
      }

      class _AddProductScreenState extends State<AddProductScreen> {
        final _formKey = GlobalKey<FormState>();
          final _nameController = TextEditingController();
            final _purchasePriceController = TextEditingController(); // <-- جديد
              final _priceController = TextEditingController();
                final _quantityController = TextEditingController();
                  final _uuid = Uuid();

                    @override
                      void dispose() {
                          _nameController.dispose();
                              _purchasePriceController.dispose(); // <-- جديد
                                  _priceController.dispose();
                                      _quantityController.dispose();
                                          super.dispose();
                                            }

                                              Future<void> _saveProduct() async {
                                                  if (_formKey.currentState!.validate()) {
                                                        final newProduct = Product()
                                                                ..id = _uuid.v4()
                                                                        ..name = _nameController.text
                                                                                ..purchasePrice = double.tryParse(_purchasePriceController.text) ?? 0.0 // <-- جديد
                                                                                        ..price = double.tryParse(_priceController.text) ?? 0.0
                                                                                                ..quantity = int.tryParse(_quantityController.text) ?? 0;

                                                                                                      final box = Hive.box<Product>('products');
                                                                                                            await box.add(newProduct);

                                                                                                                  if (mounted) {
                                                                                                                          ScaffoldMessenger.of(context).showSnackBar(
                                                                                                                                    const SnackBar(content: Text('تم حفظ المنتج بنجاح!')),
                                                                                                                                            );
                                                                                                                                                    Navigator.of(context).pop();
                                                                                                                                                          }
                                                                                                                                                              }
                                                                                                                                                                }

                                                                                                                                                                  @override
                                                                                                                                                                    Widget build(BuildContext context) {
                                                                                                                                                                        return Scaffold(
                                                                                                                                                                              appBar: AppBar(
                                                                                                                                                                                      title: const Text('إضافة منتج جديد'),
                                                                                                                                                                                            ),
                                                                                                                                                                                                  body: SingleChildScrollView(
                                                                                                                                                                                                          padding: const EdgeInsets.all(16.0),
                                                                                                                                                                                                                  child: Form(
                                                                                                                                                                                                                            key: _formKey,
                                                                                                                                                                                                                                      child: Column(
                                                                                                                                                                                                                                                  crossAxisAlignment: CrossAxisAlignment.stretch,
                                                                                                                                                                                                                                                              children: [
                                                                                                                                                                                                                                                                            TextFormField(
                                                                                                                                                                                                                                                                                            controller: _nameController,
                                                                                                                                                                                                                                                                                                            decoration: const InputDecoration(labelText: 'اسم المنتج', border: OutlineInputBorder()),
                                                                                                                                                                                                                                                                                                                            validator: (value) => (value == null || value.isEmpty) ? 'الرجاء إدخال اسم المنتج' : null,
                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                        const SizedBox(height: 16),

                                                                                                                                                                                                                                                                                                                                                                      // --- الحقل الجديد: سعر الشراء ---
                                                                                                                                                                                                                                                                                                                                                                                    TextFormField(
                                                                                                                                                                                                                                                                                                                                                                                                    controller: _purchasePriceController,
                                                                                                                                                                                                                                                                                                                                                                                                                    decoration: const InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                      labelText: 'سعر الشراء',
                                                                                                                                                                                                                                                                                                                                                                                                                                                        border: OutlineInputBorder(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          prefixIcon: Icon(Icons.shopping_cart),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          keyboardType: const TextInputType.numberWithOptions(decimal: true),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          inputFormatters: [FilteringTextInputFormatter.allow(RegExp(r'^\d+\.?\d{0,2}'))],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          validator: (value) => (value == null || value.isEmpty) ? 'الرجاء إدخال سعر الشراء' : null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const SizedBox(height: 16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // ------------------------------------

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  TextFormField(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  controller: _priceController,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  decoration: const InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    labelText: 'سعر البيع',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border: OutlineInputBorder(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        prefixIcon: Icon(Icons.attach_money),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        keyboardType: const TextInputType.numberWithOptions(decimal: true),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        inputFormatters: [FilteringTextInputFormatter.allow(RegExp(r'^\d+\.?\d{0,2}'))],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        validator: (value) => (value == null || value.isEmpty) ? 'الرجاء إدخال سعر البيع' : null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const SizedBox(height: 16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  TextFormField(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  controller: _quantityController,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  decoration: const InputDecoration(labelText: 'الكمية المتوفرة', border: OutlineInputBorder()),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  keyboardType: TextInputType.number,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  inputFormatters: [FilteringTextInputFormatter.digitsOnly],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  validator: (value) => (value == null || value.isEmpty) ? 'الرجاء إدخال الكمية' : null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const SizedBox(height: 32),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ElevatedButton.icon(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onPressed: _saveProduct,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            icon: const Icon(Icons.save, color: Colors.white),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            label: const Text('حفظ المنتج', style: TextStyle(color: Colors.white)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style: ElevatedButton.styleFrom(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              backgroundColor: Colors.green,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: const EdgeInsets.symmetric(vertical: 16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  textStyle: const TextStyle(fontSize: 18, fontFamily: 'Cairo'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          