import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'add_product_screen.dart';
import 'product_model.dart';

class ProductsScreen extends StatelessWidget {
  const ProductsScreen({super.key});

    @override
      Widget build(BuildContext context) {
          return Scaffold( // <-- تم التأكد من عدم وجود const هنا
                appBar: AppBar(
                        title: const Text("المنتجات"),
                              ),
                                    body: ValueListenableBuilder(
                                            valueListenable: Hive.box<Product>('products').listenable(),
                                                    builder: (context, Box<Product> box, _) {
                                                              if (box.values.isEmpty) {
                                                                          return buildEmptyView();
                                                                                    }
                                                                                              return buildProductsList(box.values.toList().cast<Product>());
                                                                                                      },
                                                                                                            ),
                                                                                                                  floatingActionButton: FloatingActionButton( // <-- تم التأكد من عدم وجود const هنا
                                                                                                                          onPressed: () => Navigator.of(context).push(MaterialPageRoute(builder: (_) => const AddProductScreen())),
                                                                                                                                  tooltip: 'إضافة منتج جديد',
                                                                                                                                          child: const Icon(Icons.add),
                                                                                                                                                ),
                                                                                                                                                    );
                                                                                                                                                      }

                                                                                                                                                        Widget buildEmptyView() {
                                                                                                                                                            return const Center(
                                                                                                                                                                  child: Column(
                                                                                                                                                                          mainAxisAlignment: MainAxisAlignment.center,
                                                                                                                                                                                  children: [
                                                                                                                                                                                            Icon(Icons.inventory_2_outlined, size: 60, color: Colors.grey),
                                                                                                                                                                                                      SizedBox(height: 16),
                                                                                                                                                                                                                Text('لا توجد منتجات بعد', style: TextStyle(fontSize: 18)),
                                                                                                                                                                                                                          SizedBox(height: 8),
                                                                                                                                                                                                                                    Text(
                                                                                                                                                                                                                                                'اضغط على زر "+" لإضافة أول منتج',
                                                                                                                                                                                                                                                            style: TextStyle(color: Colors.grey),
                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                              ],
                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                            Widget buildProductsList(List<Product> products) {
                                                                                                                                                                                                                                                                                                return ListView.builder(
                                                                                                                                                                                                                                                                                                      padding: const EdgeInsets.all(8),
                                                                                                                                                                                                                                                                                                            itemCount: products.length,
                                                                                                                                                                                                                                                                                                                  itemBuilder: (context, index) {
                                                                                                                                                                                                                                                                                                                          final product = products[index];
                                                                                                                                                                                                                                                                                                                                  return Card(
                                                                                                                                                                                                                                                                                                                                            child: ListTile(
                                                                                                                                                                                                                                                                                                                                                        leading: CircleAvatar(child: Text(product.quantity.toString())),
                                                                                                                                                                                                                                                                                                                                                                    title: Text(product.name),
                                                                                                                                                                                                                                                                                                                                                                                // --- هذا هو السطر المحدث لعرض سعر الشراء ---
                                                                                                                                                                                                                                                                                                                                                                                            subtitle: Text('شراء: ${product.purchasePrice} | بيع: ${product.price} ريال'),
                                                                                                                                                                                                                                                                                                                                                                                                        // ---------------------------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                    trailing: const Icon(Icons.arrow_forward_ios),
                                                                                                                                                                                                                                                                                                                                                                                                                                onTap: () {
                                                                                                                                                                                                                                                                                                                                                                                                                                              // لاحقًا: فتح شاشة تفاصيل المنتج للتعديل
                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        