import 'package:flutter/material.dart';

class ProductsScreen extends StatelessWidget {
  const ProductsScreen({super.key});

    @override
      Widget build(BuildContext context) {
          return Scaffold(
                appBar: AppBar(
                        title: const Text("المنتجات"),
                                actions: [
                                          IconButton(
                                                      onPressed: () {
                                                                    // سيتم هنا تفعيل وظيفة البحث لاحقًا
                                                                                },
                                                                                            icon: const Icon(Icons.search),
                                                                                                      ),
                                                                                                              ],
                                                                                                                    ),
                                                                                                                          body: Center(
                                                                                                                                  child: Column(
                                                                                                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                                                                                                                      children: [
                                                                                                                                                                  Icon(Icons.inventory_2_outlined, size: 60, color: Colors.grey.shade400),
                                                                                                                                                                              const SizedBox(height: 16),
                                                                                                                                                                                          const Text(
                                                                                                                                                                                                        'لا توجد منتجات بعد',
                                                                                                                                                                                                                      style: TextStyle(fontSize: 18, color: Colors.grey),
                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                              const SizedBox(height: 8),
                                                                                                                                                                                                                                                          const Text(
                                                                                                                                                                                                                                                                        'اضغط على زر "+" لإضافة أول منتج',
                                                                                                                                                                                                                                                                                      style: TextStyle(color: Colors.grey),
                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                floatingActionButton: FloatingActionButton(
                                                                                                                                                                                                                                                                                                                                        onPressed: () {
                                                                                                                                                                                                                                                                                                                                                  // سيتم هنا فتح شاشة إضافة منتج جديد لاحقًا
                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                  backgroundColor: Colors.green,
                                                                                                                                                                                                                                                                                                                                                                          tooltip: 'إضافة منتج جديد',
                                                                                                                                                                                                                                                                                                                                                                                  child: const Icon(Icons.add, color: Colors.white),
                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                              