import 'package:flutter/material.dart';

class SettingsScreen extends StatelessWidget {
  const SettingsScreen({super.key});

    @override
      Widget build(BuildContext context) {
          return Scaffold(
                appBar: AppBar(
                        title: const Text("الإعدادات"),
                              ),
                                    body: ListView(
                                            padding: const EdgeInsets.all(16.0),
                                                    children: [
                                                              ListTile(
                                                                          leading: const Icon(Icons.store_outlined),
                                                                                      title: const Text("معلومات المحل"),
                                                                                                  subtitle: const Text("اسم المحل، العنوان، الشعار"),
                                                                                                              onTap: () {},
                                                                                                                        ),
                                                                                                                                  ListTile(
                                                                                                                                              leading: const Icon(Icons.print_outlined),
                                                                                                                                                          title: const Text("إعدادات الطابعة"),
                                                                                                                                                                      onTap: () {},
                                                                                                                                                                                ),
                                                                                                                                                                                          ListTile(
                                                                                                                                                                                                      leading: const Icon(Icons.cloud_upload_outlined),
                                                                                                                                                                                                                  title: const Text("النسخ الاحتياطي والاستعادة"),
                                                                                                                                                                                                                              onTap: () {},
                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                  const Divider(height: 40),
                                                                                                                                                                                                                                                            const Center(
                                                                                                                                                                                                                                                                        child: Text(
                                                                                                                                                                                                                                                                                      "عن التطبيق",
                                                                                                                                                                                                                                                                                                    style: TextStyle(fontSize: 18, fontWeight: FontWeight.w600, color: Colors.black54),
                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                    const SizedBox(height: 20),
                                                                                                                                                                                                                                                                                                                                              Center(
                                                                                                                                                                                                                                                                                                                                                          child: Column(
                                                                                                                                                                                                                                                                                                                                                                        children: const [
                                                                                                                                                                                                                                                                                                                                                                                        Text(
                                                                                                                                                                                                                                                                                                                                                                                                          "Makzon v1.0.0",
                                                                                                                                                                                                                                                                                                                                                                                                                            style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                            SizedBox(height: 16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "🔹 برمجة وتطوير 🔹",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style: TextStyle(fontSize: 14),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                SizedBox(height: 4),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "النبراس البعداني (Alnbras Albadani)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: Colors.green),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    SizedBox(height: 8),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "للتواصل: alnbras.dev@gmail.com",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style: TextStyle(fontSize: 14, color: Colors.grey),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                